# Generated by Django 5.1.11 on 2025-07-01 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sistema_pulse"."coluna',
            },
        ),
        migrations.CreateModel(
            name='Custos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comissão')),
                ('brindes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Brindes')),
                ('imposto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Imposto')),
                ('cartao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cartão')),
            ],
            options={
                'verbose_name': 'Custos',
                'db_table': 'sistema_pulse"."custos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'sistema_pulse"."endereco',
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'sistema_pulse"."especialidade',
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
                'db_table': 'sistema_pulse"."pacote',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'sistema_pulse"."produto',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'sistema_pulse"."status',
            },
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Subtipo',
                'verbose_name_plural': 'Subtipos',
                'db_table': 'sistema_pulse"."subtipo',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'sistema_pulse"."tipo',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cadastro.coluna')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(blank=True, null=True, verbose_name='Data de Criação')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('data_cirurgia', models.DateField(blank=True, null=True, verbose_name='Data da Cirurgia')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Total')),
                ('lucro_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lucro Total')),
                ('coluna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='cadastro.coluna')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'sistema_pulse"."orcamento',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, null=True, verbose_name='Gênero')),
                ('anamnese', models.TextField(blank=True, null=True, verbose_name='Anamnese')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'sistema_pulse"."paciente',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=18, null=True, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.endereco', verbose_name='Endereço')),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.especialidade', verbose_name='Especialidade')),
                ('subtipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.subtipo', verbose_name='Subtipo')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'db_table': 'sistema_pulse"."parceiro',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoPacotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Pacote')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.orcamento', verbose_name='Orçamento')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pacote', verbose_name='Pacote')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.parceiro', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Orçamento - Pacote',
                'verbose_name_plural': 'Orçamentos - Pacotes',
                'db_table': 'sistema_pulse"."orcamento_pacotes',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.especialidade', verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'db_table': 'sistema_pulse"."procedimento',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoProcedimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.orcamento', verbose_name='Orçamento')),
                ('procedimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.procedimento', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Orçamento - Procedimentos',
                'db_table': 'sistema_pulse"."orcamento_procedimentos',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.procedimento', verbose_name='Procedimento')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Procedimento - Produto',
                'db_table': 'sistema_pulse"."procedimento_produtos',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('orcamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_orcamento', to='cadastro.orcamento', verbose_name='Orçamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.paciente', verbose_name='Paciente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Solicitação de Orçamento',
                'verbose_name_plural': 'Solicitações de Orçamento',
                'db_table': 'sistema_pulse"."solicitacao_orcamento',
            },
        ),
        migrations.AddField(
            model_name='subtipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipo', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PacoteProcedimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pacote', verbose_name='Pacote')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.procedimento', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Pacote - Procedimento',
                'verbose_name_plural': 'Pacotes - Procedimentos',
                'db_table': 'sistema_pulse"."pacote_procedimentos',
                'unique_together': {('pacote', 'procedimento')},
            },
        ),
        migrations.CreateModel(
            name='ParceiroProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_particular', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Particular')),
                ('valor_repasse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Repasse')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Venda')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.parceiro', verbose_name='Parceiro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Parceiro - Produto',
                'verbose_name_plural': 'Parceiros - Produtos',
                'db_table': 'sistema_pulse"."parceiro_produtos',
                'unique_together': {('parceiro', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='OrcamentoParceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da venda')),
                ('valor_repasse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da repasse')),
                ('margem_lucro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Margem de lucro')),
                ('custos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.custos', verbose_name='Custos')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_parceiros', to='cadastro.orcamento', verbose_name='Orçamento')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.parceiro', verbose_name='Parceiro')),
                ('produto', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Orçamento - Parceiro',
                'verbose_name_plural': 'Orçamentos - Parceiros',
                'db_table': 'sistema_pulse"."orcamento_parceiros',
                'unique_together': {('orcamento', 'parceiro', 'produto')},
            },
        ),
    ]
