# Generated by Django 5.1.5 on 2025-01-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
    ]
