# Generated by Django 5.1.11 on 2025-07-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20250701_1339'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='sistema_pulse"."card',
        ),
    ]
