# Generated by Django 5.1.6 on 2025-03-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_orcamentoparceiros_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'sistema_pulse"."produto',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.procedimento', verbose_name='Procedimento')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Procedimento - Produto',
                'db_table': 'sistema_pulse"."procedimento_produtos',
            },
        ),
    ]
