# Generated by Django 5.1.5 on 2025-01-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_paciente_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'sistema_pulse"."especialidade',
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
    ]
