# Generated by Django 5.1.11 on 2025-07-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_card_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='column',
        ),
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.RemoveField(
            model_name='card',
            name='order',
        ),
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='coluna',
        ),
        migrations.AddField(
            model_name='card',
            name='anotacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='coluna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cadastro.coluna'),
        ),
        migrations.AddField(
            model_name='card',
            name='cor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='card',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.orcamento'),
        ),
        migrations.AddField(
            model_name='card',
            name='prioridade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
