# Generated by Django 5.1.6 on 2025-03-05 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_produto_procedimentoprodutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParceiroProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_particular', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Particular')),
                ('valor_repasse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Repasse')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Venda')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.parceiro', verbose_name='Parceiro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Parceiro - Produto',
                'verbose_name_plural': 'Parceiros - Produtos',
                'db_table': 'sistema_pulse"."parceiro_produtos',
                'unique_together': {('parceiro', 'produto')},
            },
        ),
        migrations.DeleteModel(
            name='ParceiroProcedimentos',
        ),
    ]
