# Generated by Django 5.1.5 on 2025-01-16 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Subtipo',
                'verbose_name_plural': 'Subtipos',
                'db_table': 'sistema_pulse"."subtipo',
            },
        ),
    ]
