# Generated by Django 5.1.11 on 2025-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_card_column_remove_card_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custos',
            name='comissao',
        ),
        migrations.AddField(
            model_name='custos',
            name='comissao_indicacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão Indicação'),
        ),
        migrations.AddField(
            model_name='custos',
            name='comissao_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão Venda'),
        ),
    ]
