# Generated by Django 5.1.6 on 2025-03-05 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_parceiroprodutos_delete_parceiroprocedimentos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orcamentoparceiros',
            unique_together={('orcamento', 'parceiro', 'produto')},
        ),
        migrations.AddField(
            model_name='orcamentoparceiros',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto', verbose_name='Produto'),
        ),
        migrations.RemoveField(
            model_name='orcamentoparceiros',
            name='procedimento',
        ),
    ]
