# Generated by Django 5.1.6 on 2025-03-05 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_orcamentoparceiros_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoparceiros',
            name='produto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto', verbose_name='Produto'),
        ),
    ]
