# Generated by Django 5.1.7 on 2025-03-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_orcamentoparceiros_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoorcamento',
            name='orcamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_orcamento', to='cadastro.orcamento', verbose_name='Orçamento'),
        ),
    ]
