# Generated by Django 5.1.7 on 2025-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_solicitacaoorcamento_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comissão')),
                ('brindes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Brindes')),
                ('imposto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Imposto')),
                ('cartao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cartão')),
            ],
            options={
                'verbose_name': 'Custos',
                'db_table': 'sistema_pulse"."custos',
            },
        ),
    ]
