# Generated by Django 5.1.11 on 2025-10-21 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
