# Generated by Django 5.1.11 on 2025-10-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
