# Generated by Django 5.1.5 on 2025-01-16 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='valor_particular',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Particular'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParceiroProcedimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_repasse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Repasse')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.parceiro', verbose_name='Parceiro')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.procedimento', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Parceiro Procedimento',
                'verbose_name_plural': 'Parceiros Procedimentos',
                'db_table': 'sistema_pulse"."parceiro_procedimentos',
                'unique_together': {('parceiro', 'procedimento')},
            },
        ),
    ]
