# Generated by Django 5.1.7 on 2025-03-24 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_custos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Total'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_cirurgia',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Cirurgia'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='lucro_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lucro Total'),
        ),
        migrations.AddField(
            model_name='orcamentoparceiros',
            name='custos',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='cadastro.custos', verbose_name='Custos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoparceiros',
            name='margem_lucro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Margem de lucro'),
            preserve_default=False,
        ),
    ]
