# Generated by Django 5.1.5 on 2025-01-17 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_procedimento_valor_particular_parceiroprocedimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.procedimento', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'sistema_pulse"."orcamento',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoParceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.orcamento', verbose_name='Orçamento')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.parceiro', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Orçamento - Parceiro',
                'verbose_name_plural': 'Orçamentos - Parceiros',
                'db_table': 'sistema_pulse"."orcamento_parceiros',
                'unique_together': {('orcamento', 'parceiro')},
            },
        ),
    ]
