# Generated by Django 5.1.11 on 2025-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='canal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pagamento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='responsavel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_orcamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do Orçamento'),
        ),
    ]
