# Generated by Django 5.1.7 on 2025-03-24 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_orcamento_custo_total_orcamento_data_cirurgia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoparceiros',
            name='custos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.custos', verbose_name='Custos'),
        ),
    ]
