# Generated by Django 5.1.7 on 2025-03-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_orcamentoparceiros_custos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoparceiros',
            name='custos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.custos', verbose_name='Custos'),
        ),
    ]
