# Generated by Django 5.1.5 on 2025-01-17 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_orcamento_orcamentoparceiros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parceiroprocedimentos',
            options={'verbose_name': 'Parceiro - Procedimento', 'verbose_name_plural': 'Parceiros - Procedimentos'},
        ),
        migrations.CreateModel(
            name='SolicitacaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('orcamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.orcamento', verbose_name='Orçamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.paciente', verbose_name='Paciente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Solicitação de Orçamento',
                'verbose_name_plural': 'Solicitações de Orçamento',
                'db_table': 'sistema_pulse"."solicitacao_orcamento',
            },
        ),
    ]
