# Generated by Django 5.1.11 on 2025-11-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_orcamento_canal_orcamento_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome'),
        ),
    ]
