# Generated by Django 5.1.7 on 2025-04-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_orcamentoparceiros_custos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoProcedimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.orcamento', verbose_name='Orçamento')),
                ('procedimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.procedimento', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Orçamento - Procedimentos',
                'db_table': 'sistema_pulse"."orcamento_procedimentos',
            },
        ),
    ]
