# Generated by Django 5.1.14 on 2025-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='data_cirurgia',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Agendamento'),
        ),
    ]
