# Generated by Django 5.1.14 on 2025-12-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_remove_orcamento_data_cirurgia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='desconto2produto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Desconto no 2° produto (%)'),
        ),
    ]
