# Generated by Django 5.1.5 on 2025-01-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_endereco_alter_paciente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.endereco', verbose_name='Endereço'),
        ),
    ]
