# Generated by Django 5.1.14 on 2026-01-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_parceiro_desconto2produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
