# Generated by Django 5.1.5 on 2025-01-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_alter_parceiro_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='procedimento',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.status', verbose_name='Status'),
            preserve_default=False,
        ),
    ]
