# Generated by Django 5.1.14 on 2026-01-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de validade dos valores'),
        ),
    ]
