# Generated by Django 5.1.5 on 2025-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_remove_orcamento_procedimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentoparceiros',
            name='valor',
        ),
        migrations.AddField(
            model_name='orcamentoparceiros',
            name='valor_repasse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da repasse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoparceiros',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da venda'),
            preserve_default=False,
        ),
    ]
