# Generated by Django 5.1.5 on 2025-01-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_pacote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacoteProcedimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pacote', verbose_name='Pacote')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.procedimento', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Pacote - Procedimento',
                'verbose_name_plural': 'Pacotes - Procedimentos',
                'db_table': 'sistema_pulse"."pacote_procedimentos',
                'unique_together': {('pacote', 'procedimento')},
            },
        ),
    ]
