# Generated by Django 5.1.5 on 2025-01-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_pacoteprocedimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoPacotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Pacote')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.orcamento', verbose_name='Orçamento')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pacote', verbose_name='Pacote')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.parceiro', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Orçamento - Pacote',
                'verbose_name_plural': 'Orçamentos - Pacotes',
                'db_table': 'sistema_pulse"."orcamento_pacotes',
            },
        ),
    ]
