# Generated by Django 5.1.5 on 2025-02-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_orcamentopacotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='valor_particular',
        ),
    ]
