# Generated by Django 5.1.5 on 2025-02-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_remove_procedimento_valor_particular'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiroprocedimentos',
            name='valor_particular',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Particular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parceiroprocedimentos',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor de Venda'),
            preserve_default=False,
        ),
    ]
