# Generated by Django 5.1.5 on 2025-02-05 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0020_parceiroprocedimentos_valor_particular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoparceiros',
            name='procedimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.procedimento', verbose_name='Procedimento'),
        ),
        migrations.AddField(
            model_name='parceiro',
            name='cpf_cnpj',
            field=models.CharField(null=True, max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
