# Generated by Django 5.1.5 on 2025-02-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_orcamentoparceiros_procedimento_parceiro_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='cpf_cnpj',
            field=models.CharField(null=True, unique=True, max_length=11, verbose_name='CPF'),
        ),
    ]
