# Generated by Django 5.1.5 on 2025-02-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_alter_parceiro_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='cpf_cnpj',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
