# Generated by Django 5.1.6 on 2025-02-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0024_alter_parceiro_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
