# Generated by Django 5.1.6 on 2025-02-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0025_orcamento_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
