# Generated by Django 5.1.6 on 2025-02-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_alter_parceiro_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
